#!/bin/bash

METHOD="FixMatch"
CONFIDENCE_THRESHOLDS="0.85 0.90 0.95"

for CONFIDENCE_THRESHOLD in $CONFIDENCE_THRESHOLDS; do
    OUTPUT_FILE="${METHOD}-${CONFIDENCE_THRESHOLD}.txt"
    echo "Running $METHOD with confidence_threshold=$CONFIDENCE_THRESHOLD"
    python new_train.py model-$METHOD-$CONFIDENCE_THRESHOLD.pth $METHOD --confidence_threshold $CONFIDENCE_THRESHOLD > $OUTPUT_FILE
done